services:
  enterpriseoperations.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=EnterpriseOperationsDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
      - Redis__ConnectionString=redis:6379,abortConnect=false
      - ExternalSystems__OperationsApiBaseUrl=https://httpstat.us
    ports:
      - "8080:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  sqlserver:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  redis:
    ports:
      - "6379:6379"

volumes:
  sqlserver-data: